basic turtle commands and adapter to AWT window
gorttar/kotlin_start pull request #1
Opened 2019-11-29 22:28 UTC by gumanoid

2019-11-30 08:40 UTC, gorttar requested changes

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtHello.kt
> +    AwtTurtle.create().turtle pw 3 fd 50 rt 90 fd 50 rt 90 fd 50 rt 90 fd 50
Не думаю, что инфиксный синтаксический сахар здесь нужен. Его и в прод коде редко где используют, а здесь вообще библиотека, на основе которой строится обучающий курс.
Если что, другие места проекта - плохой пример в плане стиля. Было много экспериментов, далеко не все они удачные. Буду постепенно переделывать, если время появится.

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +            vararg init: JFrame.() -> Unit = arrayOf(basicInit, centerToScreen, exitOnClose, weirdDelay)
А зачем тут vararg? Одной init функции всегда и всем хватало.

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +        val basicInit = { it: JFrame ->
Здесь напрашивается тип `(JFrame).() -> Unit`, или вообще extension функция.
Ну и тип у публичной декларации лучше явно указывать.
Это же относится и к остальным init значениям

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtHello.kt
> +fun main() {
Что-то у меня рисунок появляется через раз, притом иногда только часть линий.
Надо это как-то менять. Он же должен ещё и частично как-то корректно отрисовываться, чтоб на дебаге можно было встать. Возможно имеет смысл рисование окна вынести в отдельный поток и актор.

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +class AwtTurtle<T: Component>(val component: T) {
Я как-то не очень понял, зачем нам тут дженерик? Почему не тупо `component: Component`? Да и вообще, есть ли особый смысл в классе, вся ценность которого - одно его поле? Может прям значение этого поля из create и возвращать?

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +                override fun line(x1: Float, y1: Float, x2: Float, y2: Float) {
А почему не `Double`?

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/Turtle.kt
> +    private var x: Float = 0f,
А почему не `Double`?

2019-11-30 08:40 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/Turtle.kt
> +        angle %= 360
А тут зачем остаток от деления на 360? Храни угол как есть, всё равно тригонометрия периодична.

2019-11-30 17:47 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +class AwtTurtle<T: Component>(val component: T) {
Подумал. Класс не нужен, он только лишнюю связанность между AWT и черепахой создаёт. Переделаю

2019-11-30 19:15 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtHello.kt
> +fun main() {
Надеюсь, `SwingUtils.invokeLater` нас спасёт

2019-11-30 19:17 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +            vararg init: JFrame.() -> Unit = arrayOf(basicInit, centerToScreen, exitOnClose, weirdDelay)
Думается, тут и параметр `init`  лишний. Здесь же кейс "к чёрту настройки, черепаху мне запили быыстро"

2019-11-30 19:18 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +        val basicInit = { it: JFrame ->
Согласен

2019-11-30 20:01 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtHello.kt
> +    AwtTurtle.create().turtle pw 3 fd 50 rt 90 fd 50 rt 90 fd 50 rt 90 fd 50
Здесь может и не нужен, но где-то нужен будет, в слое DSL например. Потому что черепашья программа в формате `pw 3 fd 50 rt 90 fd 50 rt 90 fd 50` смотрится лучше всего ИМХО

2019-11-30 20:14 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +                override fun line(x1: Float, y1: Float, x2: Float, y2: Float) {
А нужна такая точнсть? Тот же OpenGL весь на `Float`ах всю жизнь

2019-11-30 20:15 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/Turtle.kt
> +        angle %= 360
Перестраховываюсь. Вдруг кто провернёт черепаху миллион раз на тысячу градусов, точность начнёт теряться

2019-11-30 20:24 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtHello.kt
> +fun main() {
Таки спас

2019-11-30 20:33 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +                override fun line(x1: Float, y1: Float, x2: Float, y2: Float) {
Ну у OpenGL и задачи другие. Там не бывает глубоких рекурсивных вычисления над дробными числами.

2019-11-30 20:35 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/Turtle.kt
> +        angle %= 360
Ок

2019-11-30 20:49 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +                    EventQueue.invokeAndWait {
Минор: мб заимпортить, чтоб не писать `EventQueue` каждый раз?
Минор: мб превратить в expression body?
Те же вопросы про остальные `EventQueue.invokeAndWait`

2019-11-30 20:50 UTC, gorttar requested changes

2019-11-30 20:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +        val weirdDelay = { _: JFrame ->
Видимо это теперь стоит выпилить.

2019-11-30 21:07 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +            vararg init: JFrame.() -> Unit = arrayOf(basicInit, centerToScreen, exitOnClose, weirdDelay)
Не, сама идея `init` параметров в фабрике хорошая. Тот же размер поля для черепахи менять.
Другое дело, что мб не надо палить `init` блоку `JFrame`. Дать ему какой-нить черепахостроитель, пусть ему поля корёжит. Или вообще сделать фиксированный набор параметров  с дефолтами прям у фабрики.

2019-11-30 21:08 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/AwtHello.kt
> +    AwtTurtle.create().turtle pw 3 fd 50 rt 90 fd 50 rt 90 fd 50 rt 90 fd 50
Ну ок, пусть будет. Пущай привыкают, как говорится.

2019-11-30 21:30 UTC, gumanoid commented on src/main/kotlin/lib/graphics/turtle/AwtTurtle.kt
> +class AwtTurtle<T: Component>(val component: T) {
Распилил

2019-12-01 01:21 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/AwtTurtle.kt
> +    fun create(): Pair<Turtle, JFrame> {
А зачем нам JFrame в паре? Мы его где-нить используем?

2019-12-01 01:21 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +        graphics { stroke = BasicStroke(width) }
`BasicStroke(width, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND)`, иначе при большой ширине линии всё квадратное будет.

2019-12-01 01:21 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/AwtTurtle.kt
> +        return turtle(frame) to frame
Минор: Ох любишь ты лишнего писать без особой надобности. Ведь можно же
```Kotlin
    fun create(): Pair<Turtle, JFrame> = JFrame().apply {
        title = "Turtle"
        setSize(512, 512)
        isVisible = true

        defaultCloseOperation = JFrame.EXIT_ON_CLOSE

        val screens = GraphicsEnvironment.getLocalGraphicsEnvironment().screenDevices
        val screenRect = screens.first().defaultConfiguration.bounds
        val frameSize = size
        setLocation(
            screenRect.x + (screenRect.width - frameSize.width) / 2,
            screenRect.y + (screenRect.height - frameSize.height) / 2
        )
    }.let { turtle(it) to it }
```
без лишних `{}`, переменных и `it`.

2019-12-01 01:21 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +        operator fun invoke(block: Graphics2D.() -> Unit) {
Минор: а вот expression body не любишь почему-то...

2019-12-01 01:21 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun clear() {
И здесь

2019-12-01 01:21 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun line(x1: Float, y1: Float, x2: Float, y2: Float) {
И тут

2019-12-01 01:21 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun pen(width: Float) {
И там

2019-12-02 12:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    private var isVisible = false
Стоит перенести в `Turtle`. Не критично для мёрджа, лучше сделать отдельным PR. Я сегодня хочу смёрджить уже, чтоб падавану показать, так что это не первоочередной фикс

2019-12-02 12:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun clear() {
Лучше сделать в отдельном PR

2019-12-02 12:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +        operator fun invoke(block: Graphics2D.() -> Unit) {
Лучше сделать в отдельном PR

2019-12-02 12:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/Turtle.kt
> +    private var x: Float = 0f,
Лучше сделать в отдельном PR

2019-12-02 12:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/AwtTurtle.kt
> +        return turtle(frame) to frame
Лучше сделать в отдельном PR

2019-12-02 12:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun line(x1: Float, y1: Float, x2: Float, y2: Float) {
Лучше сделать в отдельном PR

2019-12-02 12:50 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun pen(width: Float) {
Лучше сделать в отдельном PR

2019-12-02 12:57 UTC, gorttar reviewed
Пометил не критичные изменения, без которых можно мёрджить.

2019-12-02 12:57 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/Turtle.kt
> +    private var x: Float = 0f,
Лучше сделать в отдельном PR

2019-12-02 12:57 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/AwtTurtle.kt
> +        return turtle(frame) to frame
Лучше сделать в отдельном PR

2019-12-02 12:57 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +        operator fun invoke(block: Graphics2D.() -> Unit) {
Лучше сделать в отдельном PR

2019-12-02 12:57 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    private var isVisible = false
Лучше сделать в отдельном PR

2019-12-02 12:57 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun clear() {
Лучше сделать в отдельном PR

2019-12-02 12:57 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun line(x1: Float, y1: Float, x2: Float, y2: Float) {
Лучше сделать в отдельном PR

2019-12-02 12:57 UTC, gorttar commented on src/main/kotlin/lib/graphics/turtle/awt/GraphicsTurtleCore.kt
> +    override fun pen(width: Float) {
Лучше сделать в отдельном PR

2019-12-02 17:10 UTC, merged